import pandas as pd
import re

WORDS_IN_SGOS = {
    'SGO', 'STO', 'SO', 'EAO', 'SSO', 'SFO', 'OSTC',
    'EDUCATION', 'EDUCATIONAL', 'SCHOLARSHIP', 'GRANTING', 'SCHOLARSHIPS',
    'TUITION', 'CHOICE', 'FUND', 'STUDENT', 'STUDENTS'
}
WORDS_TO_AVOID = {
    'APPRENTICESHIPS','GOD','RANCHERS','DISASTERS','FRANCE','ENFORCEMENT','FLOOD','GENOCIDE','FRENCH','NEIGHBOR','HOSPITALITY','CONTRACTS','MERCHANT','CLOTHING','SOLDIERS','RUSSIANS','PIG','LACROSSE','PEACE','GAMMA','NAUTICAL','TRAIL','JEWELERY','MUSICIANS','DAUGHTER','RESTAURANT','JEWELERS','HERITAGE','MENTEES','SISTERS','EMPTY','PRESERVE','ADULT','OUTDOORS','TRUSTEE','ALPHA','ACCREDITATION','AMBULANCE','HOCKEY','CEMETARY','ECOLOGISTS','DEALER','DIABETICS','EVENTS','ENTERPRISES','HOMESTEADS','CUSTODIANS','IMMIGRANTS','REHABILITATION','RESTORATION','UKRAINE','ORCHESTRA','REALTY','AQUARIUM','CHINESE','ELECTRICAL','SECURITY','REDUCTION','UPSILON','NEIGHBORHOOD','FIGHTERS','PRESCHOOL','COALITION','HIGH','RAPE','TELECOMMUNICATOR','SOCIETY','ABORTION','LITIGATION','SURVIVAL','CAMP','LODGING','CONGO','PREGNANCY','PSI','MIGRANT','SKATE','REHABILITATE','LAMBDA','FARMS','ELECTRICIAN','TORNADO','SHOE','ACTICITIES','CLUB','NURSING','SOCCER','HOMESCHOOLS','FOOTBALL','EVANGELISM','PI','RUSSIA','CHAPTER','RIDERS','ZOOLOGIST','KENYA','MENTORSHIP','SENATE','PAGEANT','LITERACY','STRATEGY','MARINERS','ASYLUM','ASIAN','PROFESSIONALS','PEDIATRICIANS','PROSTHODONTIST','DEATH','ENTERPRISE','DENTAL','DELTA','SCIENCE','WRITING','HOTLINE','HOUSING','BOOSTERS','ASIA','TENNIS','EQUIPMENT','TRUSTEES','REFUGEE','CONSERVATION','OMIKRON','OMICRON','ALCOHOL','OSTEOPATHIC','MIDWIFERY','ENVIRONMENTAL','RANCH','CREDIT','CRISIS','RADIO','RICAN','RIDER','FLOODS','CLINICAL','ANIMAL','ANDEAN','UKRANIAN','HOMESTEADERS','JOURNALISM','CAMBODIA','HANDICAP','HOMESCHOOL','AVIATORS','ALUMNUS','CONSULTATION','SKATEPARKS','CLEAN','MARINE','ENDANGERED','SWEDISH','TOURISM','MUSEUMS','ENFORCERS','FARM','NEIGHBOUR','SPORT','MINISTRY','SHEET','GREENHOUSE','CHOIRS','HEPATITIS','ARMY','RECREATION','COMMEMORATION','AFRICAS','CONGOLESE','WILDLIFE','WOUNDED','SYMPHONY','COMMEMORATIVE','NAVY','VIOLENCE','AFRICAN','MEDICINE','ADVOCATES','EMPLOYERS','DEVELOPMENT','RELOCATION','ECONOMIC','ISLAMIC','DISABILITIES','IRON','PEDESTRIAN','MUSICIAN','MIDWIVES','HOMESTEAD','VETERANS','INDIAN','BAIL','ENTREPRENEURS','SKATERS','DANCING','MENTEE','MILK','ATHLETIC','PHILANTHROPY','EPSILON','CONSULTANT','ZIMBABWE','DENTISTRY','HAITI','ETA','RETREATS','HINDU','RESCUE','PHILANTHROPIC','TORNADOS','CONSULTING','GLOBAL','HIV','CLINICS','INJURED','BALLET','BASKET','ARK','NEUROPSYCHOLOGICAL','SEMINARY','WELLNESS','FAMILY','ART','REMEMBRANCE','CATASTROPHIC','THERAPEUTIC','HISTORY','INSTRUMENTS','DISCRETIONARY','GREENHOUSES','NURSES','JEWELER','DEFENCE','ESTATES','SENATORS','VOLLEYBALL','SNOWMOBILE','MUSIC','SANITARY','MEDIA','APPRENTICESHIP','ENDOWMENT','SURGEON','CARE','CIVIC','PRESERVATION','PARENT','SINGLE','ENGINEERS','GERONTOLOGY','ENTERTAINMENT','FIREFIGHTERS','POOR','ZOOLOGICAL','MUSLIMS','HOMELESSNESS','NATURE','RACIAL','FIREMENS','CIVICS','CULTURAL','AGRICULTURE','SUMMER','TRAVEL','SYNDROME','COIFFEUR','DISABILITY','DEMOCRATIC','DRUG','OSTEOPATHY','HOPE','PEDIATRIC','CHARITABLE','ENCAMPMENT','CONSORTIUM','IOTA','PET','XI','ADDICTION','PROM','EVENT','PEST','DYSLEXIA','DYSLEXIC','CONCILIATION','GUN','ORTHODONTIST','FUNERAL','TELECOMMUNICATION','FITNESS','FOOD','HUNTING','UKRAINIANS','TELECOMMUNICATORS','DIVISION','LEGAL','CONSTRUCTION','FIGHTER','REALTOR','ZOOLOGISTS','ETHICAL','PROSTHODONTISTS','AWARENESS','HONDURAS','BED','ARABIC','ARTS','INDUSTRY','MU','DANCERS','ISLAM','CORRECTIONS','SENATOR','BROTHERHOOD','AUTISM','ENVIRONMENT','RESPONDERS','REMEMBERANCE','ELECTRICITY','FIREFIGHTER','WIDOW','HUMANITY','LECTURE','RETREAT','CARPENTERS','ACTIVITIES','CUSTODIAN','AGENCIES','CHURCH','EMERGENCY','MILITARY','ENTREPRENEURSHIP','HOMESTEADER','PARENTS','LEGACY','THEATRE','GUILD','HISTORIC','GUARD','CHRISTMAS','PLAYGROUND','MENTOR','BASKETBALL','ELECTRICIANS','SOLDIER','PARKS','PREVENTION','BASEBALL','LEAGUE','FIREFIGHTING','ELDERLY','EMPOWER','SOFTBALL','TOWNSHIP','BOOSTER','HOSPITAL','GOSPEL','ENSEMBLE','MERCHANTS','RHO','TRIP','RECOVERY','PSYCHOLOGY','DYSLEXICS','DRUGS','MORALE','INCORPORATED','MARINER','MARINES','INDIA','ALLIANCE','VOTER','CHORUS','LAW','HOMELESS','SURGEONS','RESIDENTIAL','MINISTRIES','APPRENTICE','AVIATION','SAILING','AQUATIC','BETA','SISTERHOOD','MISSIONARY','HABITAT','THERAPY','HOLOCAUST','JEWISH','DEFENSES','SOLES','CHARITY','WRITE','VENTURE','DEAF','MANAGEMENT','TORNADOES','RACE','SKATEPARK','HAITIAN','PERU','SKATER','ACQUATIC','AMBULANCES','MENS','COW','LEGION','GOLF','TELEVISION','BOAT','SAFETY','ZOO','MEMORIAL','CITIZENSHIP','RETIRED','APPRENTICES','KAPPA','AFRICA','CONSULTANTS','TRAINING','PROFESSIONAL','BILINGUAL','WATCHMAKERS','PTO','JUSTICE','CONSUMER','DISABLED','MEN','COMPUTER','IMPROVEMENT','PRIMARY','YMCA','CLOTHED','DANCE','ESTATE','MARRIAGE','CHI','GERIATRIC','LOAN','WAR','CLOTHES','CRIPPLED','CARPENTRY','COMPENSATION','NUTRITIONAL','CARPENTER','NEIGHBORHOODS','TRANSGENDER','REHAB','NEIGHBOURHOODS','CONTRACT','YWCA','DIABETIC','DAUGHTERS','EARTHQUAKE','VOTE','WIDOWS','PERSONS','POLICE','CHEFS','CHOIR','ADVOCACY','CHESS','HOMESCHOOLERS','SHARECROPPING','CHINA','WORLDWIDE','DEPARTMENT','FIREMEN','ALUMNI','VETERAN','ALPINE','HOMESCHOOLER','TEMPERANCE','SHARECROPPERS','NU','TOY','SUPPORT','AUTISTIC','FINANCE','WOMEN','WOMAN','HEALTHCARE','RACING','RELIEF','WIDOWED','TAX','TAU','WIDOWERS','WIDOWER','DEER','SAIL','VIOLENT','ENERGY','ECOLOGIST','PASTORAL','AGENCY','MENTORS','TOYS','BLACKS','SPORTS','MENTORING','ACCIDENT','OMEGA','UNHOUSED','HISTORICAL','THETA','VOLUNTEER','CATASTROPHE','HOME','ORTHODONTISTS','UKRAINIAN','THEATER','TOURNAMENT','ISRAEL','ESTEEMED','PHI','SHOOTING','GARDEN','HUNTER','HUNTERS','NEIGHBOURHOOD','GAY','BOATING','BOWLING','MUSEUM','SWIMMING','FALLEN','AGRICULTURAL','DEFENCES','ENGINEER','MIDDLE','ARAB','PEDIATRICIAN','FELLOWSHIP','ATHLETICS','BURNED','LIGHTHOUSE','DEFENSE','CONTRACTOR','SNOWSPORTS','SANITATION','MARRIAGES','HANDICAPPED','PENALTY','CEMETERY','ELECTRIC','GOURMET','PAWS','DIABETES','ORPHANAGE','PONY','ANIMALS','SERVICES','RANCHES','RANCHER','REALTORS','CARIBBEAN','RESIDENT','STEM','SIGMA','VOTERS','MENTORSHIPS','DENTISTS','HEALTH','NURSE','FILIPINO','SHARECROPPER','INDUSTRIAL','SISTER','EARTHQUAKES','JEWELRY','EMPLOYER','ROBOTICS','MIDWIFE','MEDICAL','PRIDE','SPIRITUAL','TORAH','DISASTER','ROTARY','RESEARCH','CLINCAL','CELL','CONTRACTORS','GOVERNMENT','PSYCHOLOGICAL','OUTDOOR','SECONDARY','SILENCE','LANKA','COUNTY','PARK','RUSSIAN','ENGINEERING','MOTORSPORTS','MALARIA','LATIN','CANCER','CONTROL','ECOLOGY','ZETA','BUREAU','ESTEEM','WOMEN\'S','WOMAN\'S','AMATEUR','DENTIST','ATHLETES','SKI','DEALERS','NUTRITION','COMMUNITY','MUSLIM','CLINIC'
}
NAME_TOKEN_PATTERN = re.compile(r"\b[\w']+\b")


def filter_by_name(df, name_column='NAME'):
    """Keep only rows whose NAME contains a keyword from WORDS_IN_SGOS."""
    if name_column not in df.columns:
        return df.copy()

    def has_sgolike_token(name):
        if pd.isna(name):
            return False

        tokens = NAME_TOKEN_PATTERN.findall(str(name).upper())
        return any(token in WORDS_IN_SGOS for token in tokens)

    return df[df[name_column].apply(has_sgolike_token)].copy()


def filter_out_avoid_words(df, name_column='NAME'):
    """Remove rows whose NAME contains any word from WORDS_TO_AVOID."""
    if name_column not in df.columns:
        return df.copy()

    def has_avoid_word(name):
        if pd.isna(name):
            return False

        tokens = NAME_TOKEN_PATTERN.findall(str(name).upper())
        return any(token in WORDS_TO_AVOID for token in tokens)

    return df[~df[name_column].apply(has_avoid_word)].copy()


def filter_organizations(df):
    """
    Filter organizations based on criteria.
    Organizations must meet at least 5 of the following 6 criteria to be kept.
    """
    # Define the valid values for each criterion
    valid_ntee_codes = ['B01', 'B12', 'B20', 'B21', 'B24', 'B25', 'B82', 'B90', 'B99',
                        'P20', 'P82', 'P84', 'T30', 'T31', 'T99', 'W05']
    valid_subsection = 3
    valid_affiliation = [3, 9]
    valid_classification = [1000, 1200, 1700, 2000]
    valid_deductibility = 1
    valid_foundation = [10, 15, 16]

    def count_criteria_met(row):
        """Count how many criteria a row meets."""
        criteria_count = 0

        # Criterion 1: NTEE_CD
        if 'NTEE_CD' in row.index:
            ntee_value = str(row['NTEE_CD']).strip()
            if ntee_value in valid_ntee_codes or ntee_value == '0' or ntee_value == '' or pd.isna(row['NTEE_CD']):
                criteria_count += 1

        # Criterion 2: SUBSECTION
        if 'SUBSECTION' in row.index:
            if pd.notna(row['SUBSECTION']) and row['SUBSECTION'] == valid_subsection:
                criteria_count += 1

        # Criterion 3: AFFILIATION
        if 'AFFILIATION' in row.index:
            if pd.notna(row['AFFILIATION']) and row['AFFILIATION'] in valid_affiliation:
                criteria_count += 1

        # Criterion 4: CLASSIFICATION
        if 'CLASSIFICATION' in row.index:
            if pd.notna(row['CLASSIFICATION']) and row['CLASSIFICATION'] in valid_classification:
                criteria_count += 1

        # Criterion 5: DEDUCTIBILITY
        if 'DEDUCTIBILITY' in row.index:
            if pd.notna(row['DEDUCTIBILITY']) and row['DEDUCTIBILITY'] == valid_deductibility:
                criteria_count += 1

        # Criterion 6: FOUNDATION
        if 'FOUNDATION' in row.index:
            if pd.notna(row['FOUNDATION']) and row['FOUNDATION'] in valid_foundation:
                criteria_count += 1

        return criteria_count

    # Apply the criteria check to each row
    df['criteria_met'] = df.apply(count_criteria_met, axis=1)

    # Filter to keep only rows meeting at least 5 criteria
    filtered_df = df[df['criteria_met'] >= 5].copy()

    # Drop the temporary criteria_met column
    filtered_df = filtered_df.drop(columns=['criteria_met'])

    return filtered_df